In [11]:
import numpy as np
a = np.array([1,12,3])
print(type(a))

print(a.shape)


print(a[0],a[1],a[2])


a[0]

print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)


<class 'numpy.ndarray'>
(3,)
1 12 3
[ 1 12  3]
(2, 3)


In [17]:
import numpy as np
a=np.random.random((4,3))#It will create random genetated values in the matrix of order 4x3
print(a,"\n*****************************************")
b=np.random.random((4,3,2)) #It will create random generated values in 4 matrices of order 3x2
print(b)

[[0.67018493 0.35359589 0.18517304]
 [0.10637566 0.10410731 0.77589783]
 [0.82005656 0.5829081  0.36205233]
 [0.64997359 0.90300949 0.9962758 ]] 
*****************************************
[[[0.22289295 0.4488254 ]
  [0.74723392 0.14122194]
  [0.98049036 0.68274973]]

 [[0.67803638 0.73520023]
  [0.41836657 0.00957488]
  [0.6927486  0.88286349]]

 [[0.74503858 0.69431907]
  [0.69074941 0.54561658]
  [0.98411569 0.40638595]]

 [[0.98341013 0.8814834 ]
  [0.11465817 0.47859278]
  [0.67943882 0.8527656 ]]]


In [34]:
import numpy as np
a = np.array([[5,6,7],[1,2,3],[8,-1,4]])

b= np.array([[2,4,3],[1,8,5],[99,2,3]])
#it will give all the values which is greater than 3
print(a[a>3])
print("*********************")
c= np.array([[2,4,3],[1,8,5],[99,2,3]])
#It will check the cond. of greater than 3
print(a>3)
print("*********************")
m = np.multiply(a,b,c)
print(m)



[5 6 7 8 4]
*********************
[[ True  True  True]
 [False False False]
 [ True False  True]]
*********************
[[ 10  24  21]
 [  1  16  15]
 [792  -2  12]]
